# Generated by Django 6.0.6 on 2026-06-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_gr', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('university_gr', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('topics', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('ects', models.IntegerField()),
                ('semesters', models.IntegerField()),
                ('tuition', models.CharField(max_length=30)),
                ('study_modes', models.JSONField(default=list)),
                ('email', models.EmailField(max_length=50)),
                ('scholarship', models.BooleanField()),
                ('university_image_url', models.URLField()),
                ('programme_url', models.URLField()),
                ('open_date', models.DateField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('intake', models.CharField(max_length=30)),
                ('apply_url', models.URLField(max_length=1000)),
                ('application_status', models.CharField(choices=[('closed', 'Closed'), ('coming_soon', 'Coming Soon'), ('missing', 'No Date'), ('open', 'Open'), ('error', 'Error'), ('rolling', 'Rolling'), ('found', 'Dates')], default='missing', max_length=20)),
                ('notes', models.TextField(blank=True, default='', max_length=1000)),
                ('portal', models.TextField(blank=True, default='', max_length=100)),
                ('requires_login', models.BooleanField()),
                ('found', models.BooleanField()),
                ('found_in_announcement', models.BooleanField()),
                ('scrape_status', models.CharField(choices=[('ok', 'Ok'), ('skipped', 'Skipped')], default='skipped', max_length=20)),
                ('pass2_status', models.CharField(choices=[('ok', 'Ok'), ('skipped', 'Skipped')], default='skipped', max_length=20)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('atsig_url', models.URLField()),
            ],
        ),
    ]
