# Generated by Django 6.0.6 on 2026-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='application_status',
            field=models.CharField(choices=[('closed', 'Closed'), ('coming_soon', 'Coming Soon'), ('missing', 'No Date'), ('open', 'Open'), ('error', 'Error'), ('rolling', 'Rolling'), ('found', 'Dates'), ('not_mentioned', 'Not Mentioned')], default='missing', max_length=20),
        ),
        migrations.AlterField(
            model_name='programme',
            name='apply_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='programme',
            name='atsig_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='programme',
            name='ects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='found_in_announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='programme',
            name='requires_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='scholarship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='semesters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='tuition',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='university_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
