# Generated by Django 6.0.6 on 2026-06-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_programme_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
