# Generated by Django 6.0.6 on 2026-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_programme_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='deadline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='programme',
            name='open_date',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
