# Generated by Django 6.0.6 on 2026-07-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_programme_deadline_alter_programme_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='intake',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programme',
            name='tuition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
