# Generated by Django 6.0.6 on 2026-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_programme_intake_alter_programme_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='intake',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
