# Generated by Django 6.0.6 on 2026-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_programme_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='name_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name_gr',
            field=models.CharField(max_length=200),
        ),
    ]
