# Generated by Django 6.0.6 on 2026-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_programme_name_en_alter_programme_name_gr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='atsig_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='programme',
            name='university_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
